name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  security-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    permissions:
      # Required for uploading SARIF results
      security-events: write
      # Required for checking out the code
      contents: read
      # Required for posting PR comments
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: |
            go.sum

      - name: Download Go modules
        run: go mod download

      - name: Build extension
        run: make build
        
      - name: Run Trivy for SARIF report
        uses: aquasecurity/trivy-action@0.32.0
        id: trivy_sarif_scan
        with:
          scan-type: 'fs'
          scan-ref: './extensions/newrelic-lambda-extension'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          scanners: 'vuln,secret,config'
        continue-on-error: true

      - name: Run Trivy for PR comment
        if: github.event_name == 'pull_request'
        uses: aquasecurity/trivy-action@0.32.0
        id: trivy_comment_scan
        with:
          scan-type: 'fs'
          scan-ref: './extensions/newrelic-lambda-extension'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          scanners: 'vuln,secret,config'

      - name: Upload Trivy SARIF report to GitHub Security tab
        
        if: always() 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Comment on PR with Trivy results
        if: ${{ github.event_name == 'pull_request' && steps.trivy_sarif_scan.outcome == 'failure' }}
        uses: actions/github-script@v7
        with:
          script: |
            const table = `${{ steps.trivy_comment_scan.outputs.stdout }}`;
            const commentBody = `## 🔒 Trivy Security Scan Results

            ⚠️ **Vulnerabilities have been detected in this pull request.**

            Please review the summary below and check the [Security tab](https://github.com/${{ github.repository }}/security/code-scanning) for full details.

            <details>
            <summary>Click to view Vulnerability Summary Table</summary>

            \`\`\`
            ${table}
            \`\`\`

            </details>
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });

      - name: Fail workflow if vulnerabilities were found
        # This is the final step that will fail the check if the main SARIF scan failed.
        if: ${{ steps.trivy_sarif_scan.outcome == 'failure' }}
        run: |
          echo "❌ Trivy detected security vulnerabilities!"
          echo "Please review the scan results and address the issues."
          exit 1
